# Generated by Django 6.0.6 on 2026-06-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant du clip (export).', max_length=60, unique=True)),
                ('titre', models.CharField(blank=True, help_text='Usage interne uniquement, non montré au participant.', max_length=200)),
                ('fichier_video', models.CharField(help_text='Chemin relatif sous MEDIA_ROOT, ex. videos/clip_042.mp4', max_length=300)),
                ('fichier_vtt', models.CharField(blank=True, help_text='Chemin relatif du sous-titre WebVTT, ex. videos/clip_042.vtt', max_length=300)),
                ('categorie', models.CharField(blank=True, help_text="Métadonnée libre pour l'analyse (condition, source...).", max_length=80)),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour exclure du tirage.')),
                ('nb_evaluations', models.PositiveIntegerField(default=0, help_text='Compteur mis à jour à chaque jugement (sert au tirage pondéré).')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton', models.CharField(db_index=True, help_text='Identifiant anonyme stable de session.', max_length=64, unique=True)),
                ('consentement', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identifiant court et stable, utilisé comme en-tête de colonne à l'export (ex. q1, age, clarte).", max_length=40, unique=True)),
                ('libelle', models.CharField(help_text='Texte affiché au participant.', max_length=400)),
                ('type', models.CharField(choices=[('echelle', 'Échelle numérique'), ('choix', 'Choix (une ou plusieurs options)'), ('texte', 'Texte libre')], default='echelle', max_length=20)),
                ('aide', models.CharField(blank=True, help_text="Texte d'aide optionnel sous la question.", max_length=400)),
                ('min_val', models.IntegerField(blank=True, null=True)),
                ('max_val', models.IntegerField(blank=True, null=True)),
                ('label_min', models.CharField(blank=True, help_text='Libellé sous la borne basse (ex. Pas du tout clair).', max_length=80)),
                ('label_max', models.CharField(blank=True, help_text='Libellé sous la borne haute (ex. Très clair).', max_length=80)),
                ('choix_multiple', models.BooleanField(default=False, help_text='Si coché, plusieurs options sélectionnables.')),
                ('obligatoire', models.BooleanField(default=True)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage croissant.")),
                ('active', models.BooleanField(default=True, help_text='Décocher pour retirer la question sans la supprimer.')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Jugement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, help_text='Horodatage de soumission des réponses.', null=True)),
                ('enregistrement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jugements', to='etude.enregistrement')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugements', to='etude.participant')),
            ],
            options={
                'ordering': ['debut'],
                'unique_together': {('participant', 'enregistrement')},
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(help_text='Valeur enregistrée (ex. voix).', max_length=80)),
                ('libelle', models.CharField(help_text='Texte affiché (ex. Une voix humaine).', max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='etude.question')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(blank=True)),
                ('jugement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='etude.jugement')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etude.question')),
            ],
            options={
                'unique_together': {('jugement', 'question')},
            },
        ),
    ]
