# Generated by Django 6.0.6 on 2026-06-09 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etude', models.CharField(default='Étude', help_text="Nom de l'étude (titres de page, en-tête de l'administration).", max_length=200)),
                ('titre_accueil', models.CharField(default='Bienvenue', help_text='Titre affiché sur la page de consentement.', max_length=200)),
                ('description', models.TextField(default='Vous allez participer à une étude. Lisez les informations ci-dessous, puis indiquez votre consentement pour commencer.\n\nVos réponses sont enregistrées de façon anonyme et utilisées uniquement dans le cadre de cette recherche.', help_text='Texte de présentation / consentement (sauts de ligne respectés).')),
                ('bouton_consentement', models.CharField(default='Je consens et je commence', help_text='Libellé du bouton de consentement.', max_length=100)),
                ('intro_profil', models.TextField(blank=True, default="Ces questions ne sont posées qu'une seule fois et servent uniquement aux statistiques de l'étude. Vos réponses restent anonymes.", help_text="Texte d'introduction de la page de profil.")),
                ('texte_remerciement', models.TextField(default='Merci pour votre participation. Vos réponses ont bien été enregistrées ; vous pouvez fermer cette page.', help_text='Texte de la page de fin.')),
                ('ordre_groupes_aleatoire', models.BooleanField(default=True, help_text='Si coché, les groupes sont proposés dans un ordre aléatoire (pondéré pour équilibrer la couverture). Sinon, dans leur ordre défini.')),
                ('max_groupes', models.PositiveIntegerField(default=0, help_text="Nombre maximal de groupes proposés à un participant (0 = illimité, jusqu'à épuisement).")),
            ],
            options={
                'verbose_name': "configuration de l'étude",
                'verbose_name_plural': "configuration de l'étude",
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant court du média.', max_length=60, unique=True)),
                ('titre', models.CharField(blank=True, help_text='Usage interne.', max_length=200)),
                ('type_media', models.CharField(choices=[('video', 'Vidéo'), ('audio', 'Audio')], default='video', max_length=10)),
                ('fichier', models.CharField(help_text='Chemin relatif sous MEDIA_ROOT, ex. medias/q_voix.mp3', max_length=300)),
                ('vtt', models.CharField(blank=True, help_text='Chemin relatif du sous-titre WebVTT (optionnel).', max_length=300)),
            ],
            options={
                'verbose_name': 'média',
                'verbose_name_plural': 'médias',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jeton', models.CharField(db_index=True, help_text='Identifiant anonyme stable de session.', max_length=64, unique=True)),
                ('consentement', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, help_text='Titre de section affiché au participant (optionnel).', max_length=200)),
                ('consigne', models.TextField(blank=True, help_text='Consigne / introduction du groupe (optionnel).')),
                ('portee', models.CharField(choices=[('standard', 'Standard (tiré dans la boucle)'), ('profil', 'Profil (posé une seule fois au début)')], default='standard', help_text='« Profil » : posé une seule fois au début. « Standard » : tiré dans la boucle.', max_length=10)),
                ('inclure_tirage', models.BooleanField(default=True, help_text='Si décoché, ce groupe standard est exclu du tirage (utile pour une intro épinglée).')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre (croissant) ; utilisé si le tirage n'est pas aléatoire.")),
                ('active', models.BooleanField(default=True, help_text='Décocher pour masquer le groupe sans le supprimer.')),
                ('nb_evaluations', models.PositiveIntegerField(default=0, help_text='Nombre de fois répondu (sert au tirage pondéré).')),
                ('media', models.ForeignKey(blank=True, help_text='Vidéo unique du groupe, affichée en permanence à gauche (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupes', to='etude.media')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Code remis à un participant. Laisser vide pour en générer un automatiquement.', max_length=64, unique=True)),
                ('note', models.CharField(blank=True, help_text="Repère interne (destinataire, vague d'envoi...). Jamais montré au participant.", max_length=200)),
                ('collectif', models.BooleanField(default=False, help_text='Si coché : lien collectif à partager largement (chaque visiteur devient un nouveau participant). Sinon : code individuel lié à une personne.')),
                ('actif', models.BooleanField(default=True, help_text="Décocher pour révoquer l'accès.")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(blank=True, help_text='Participant associé, pour un code individuel (vide pour un lien collectif).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_acces', to='etude.participant')),
            ],
            options={
                'verbose_name': "code d'accès",
                'verbose_name_plural': "codes d'accès",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField(auto_now_add=True)),
                ('fin', models.DateTimeField(blank=True, help_text='Horodatage de fin du groupe.', null=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passages', to='etude.groupe')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='etude.participant')),
            ],
            options={
                'ordering': ['debut'],
                'unique_together': {('participant', 'groupe')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Identifiant court et stable, utilisé comme en-tête de colonne à l'export (ex. q1, age, clarte).", max_length=40, unique=True)),
                ('libelle', models.CharField(help_text='Texte affiché au participant.', max_length=400)),
                ('type', models.CharField(choices=[('echelle', 'Échelle numérique'), ('choix', 'Choix (cases / boutons radio)'), ('cartes', 'Cartes (choix en cartes détaillées)'), ('matrice', 'Matrice (sous-questions × catégories)'), ('dragdrop', 'Classement par glisser-déposer'), ('texte', 'Texte court'), ('longtext', 'Texte long')], default='echelle', max_length=20)),
                ('aide', models.CharField(blank=True, help_text="Texte d'aide optionnel sous la question.", max_length=400)),
                ('min_val', models.IntegerField(blank=True, null=True)),
                ('max_val', models.IntegerField(blank=True, null=True)),
                ('label_min', models.CharField(blank=True, help_text='Libellé sous la borne basse (ex. Pas du tout).', max_length=80)),
                ('label_max', models.CharField(blank=True, help_text='Libellé sous la borne haute (ex. Tout à fait).', max_length=80)),
                ('choix_multiple', models.BooleanField(default=False, help_text='Si coché, plusieurs options sélectionnables (choix / cartes).')),
                ('melanger', models.BooleanField(default=False, help_text="Mélanger l'ordre des options / catégories (rotation) pour chaque participant.")),
                ('longueur', models.IntegerField(blank=True, help_text='Longueur indicative pour les champs texte (optionnel).', null=True)),
                ('obligatoire', models.BooleanField(default=True)),
                ('saut_de_page', models.BooleanField(default=False, help_text='Si coché, cette question commence un nouvel écran (un bouton « Suivant » apparaît avant elle).')),
                ('ordre', models.IntegerField(default=0, help_text='Ordre dans le groupe (croissant).')),
                ('active', models.BooleanField(default=True, help_text='Décocher pour retirer la question sans la supprimer.')),
                ('groupe', models.ForeignKey(blank=True, help_text='Groupe auquel appartient la question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='etude.groupe')),
                ('media', models.ForeignKey(blank=True, help_text='Média audio/vidéo propre à cette question (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='etude.media')),
            ],
            options={
                'ordering': ['groupe__ordre', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(help_text='Valeur enregistrée (ex. oui, AO01).', max_length=80)),
                ('libelle', models.CharField(help_text='Texte affiché (ex. Oui, tout à fait).', max_length=200)),
                ('description', models.CharField(blank=True, help_text='Détail affiché sous le libellé (cartes).', max_length=300)),
                ('ordre', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='etude.question')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SousQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant export (ex. BLUE_SQ001).', max_length=60, unique=True)),
                ('libelle', models.CharField(help_text='Intitulé de la ligne (ex. Primary Role).', max_length=300)),
                ('ordre', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_questions', to='etude.question')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReponseProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_profil', to='etude.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etude.question')),
            ],
            options={
                'unique_together': {('participant', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(blank=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='etude.passage')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etude.question')),
                ('sous_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='etude.sousquestion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('passage', 'question', 'sous_question'), name='reponse_unique_passage_question_sousq')],
            },
        ),
    ]
