# Generated by Django 6.0.6 on 2026-06-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choix',
            name='libelle',
            field=models.CharField(help_text='Texte affiché au participant (ex. Oui, tout à fait).', max_length=200),
        ),
        migrations.AlterField(
            model_name='choix',
            name='valeur',
            field=models.CharField(blank=True, help_text="Valeur enregistrée à l'export. Laisser vide = reprend le libellé (utile surtout pour des codes, ex. AO01).", max_length=80),
        ),
    ]
