# Generated by Django 6.0.6 on 2026-06-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Code remis à un participant. Laisser vide pour en générer un automatiquement.', max_length=64, unique=True)),
                ('note', models.CharField(blank=True, help_text="Repère interne (destinataire, vague d'envoi...). Jamais montré au participant.", max_length=200)),
                ('actif', models.BooleanField(default=True, help_text="Décocher pour révoquer l'accès.")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(blank=True, help_text='Participant associé (rempli à la première utilisation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_acces', to='etude.participant')),
            ],
            options={
                'verbose_name': "code d'accès",
                'verbose_name_plural': "codes d'accès",
                'ordering': ['code'],
            },
        ),
    ]
