# Generated by Django 6.0.6 on 2026-06-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude', '0002_codeacces'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeacces',
            name='collectif',
            field=models.BooleanField(default=False, help_text='Si coché : lien collectif à partager largement (chaque visiteur devient un nouveau participant). Sinon : code individuel lié à une personne.'),
        ),
        migrations.AlterField(
            model_name='codeacces',
            name='participant',
            field=models.OneToOneField(blank=True, help_text='Participant associé, pour un code individuel (vide pour un lien collectif).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_acces', to='etude.participant'),
        ),
    ]
