# Generated by Django 6.0.6 on 2026-06-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude', '0003_codeacces_collectif_alter_codeacces_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, help_text='Titre de section affiché au participant (optionnel).', max_length=200)),
                ('consigne', models.TextField(blank=True, help_text="Consigne / texte d'introduction du groupe (optionnel).")),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage croissant.")),
                ('nouvelle_page', models.BooleanField(default=False, help_text='Si coché, ce groupe commence une nouvelle page (sinon il suit le précédent sur la même page).')),
                ('active', models.BooleanField(default=True, help_text='Décocher pour masquer le groupe sans le supprimer.')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant court du média.', max_length=60, unique=True)),
                ('titre', models.CharField(blank=True, help_text='Usage interne.', max_length=200)),
                ('type_media', models.CharField(choices=[('video', 'Vidéo'), ('audio', 'Audio')], default='video', max_length=10)),
                ('fichier', models.CharField(help_text='Chemin relatif sous MEDIA_ROOT, ex. medias/q_voix.mp3', max_length=300)),
                ('vtt', models.CharField(blank=True, help_text='Chemin relatif du sous-titre WebVTT (optionnel).', max_length=300)),
            ],
            options={
                'verbose_name': 'média de question',
                'verbose_name_plural': 'médias de question',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['groupe__ordre', 'ordre', 'id']},
        ),
        migrations.AlterField(
            model_name='question',
            name='ordre',
            field=models.IntegerField(default=0, help_text='Ordre dans le groupe (croissant).'),
        ),
        migrations.AddField(
            model_name='question',
            name='groupe',
            field=models.ForeignKey(blank=True, help_text='Groupe (section) auquel appartient la question.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='etude.groupe'),
        ),
        migrations.AddField(
            model_name='question',
            name='media',
            field=models.ForeignKey(blank=True, help_text='Média audio/vidéo propre à cette question (optionnel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='etude.media'),
        ),
    ]
