# Generated by Django 6.0.6 on 2026-06-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etude", "0003_sousquestion_code_optionnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="continuer_bouton_arreter",
            field=models.CharField(
                default="M'arrêter ici",
                help_text="Libellé du bouton « s'arrêter ».",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="continuer_bouton_continuer",
            field=models.CharField(
                default="Continuer",
                help_text="Libellé du bouton « continuer ».",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="continuer_bouton_terminer",
            field=models.CharField(
                default="Terminer",
                help_text="Libellé du bouton « terminer ».",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="continuer_texte_fin",
            field=models.CharField(
                default="Vous avez répondu à toutes les questions disponibles. Merci pour votre participation.",
                help_text="Texte affiché quand il n'y a plus de groupe disponible.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="continuer_texte_suite",
            field=models.CharField(
                default="Souhaitez-vous continuer ou vous arrêter ici ?",
                help_text="Texte affiché quand il reste des groupes à faire.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="configuration",
            name="continuer_titre",
            field=models.CharField(
                default="Merci, c'est noté.",
                help_text="Titre de la page intermédiaire après chaque groupe.",
                max_length=200,
            ),
        ),
    ]
