# Generated by Django 6.0.6 on 2026-06-09 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude', '0004_groupe_media_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='portee',
            field=models.CharField(choices=[('extrait', 'Par extrait (rattachée à chaque jugement)'), ('profil', 'Profil participant (posée une seule fois)')], default='extrait', help_text='« Profil » : posée une fois au participant (âge, genre...). « Par extrait » : posée pour chaque extrait évalué.', max_length=10),
        ),
        migrations.CreateModel(
            name='ReponseProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_profil', to='etude.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='etude.question')),
            ],
            options={
                'unique_together': {('participant', 'question')},
            },
        ),
    ]
