# Generated by Django 6.0.6 on 2026-06-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude', '0005_question_portee_reponseprofil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etude', models.CharField(default='Étude', help_text="Nom de l'étude (titres de page, en-tête de l'administration).", max_length=200)),
                ('titre_accueil', models.CharField(default='Bienvenue', help_text='Titre affiché sur la page de consentement.', max_length=200)),
                ('description', models.TextField(default='Vous allez participer à une étude. Lisez les informations ci-dessous, puis indiquez votre consentement pour commencer.\n\nVos réponses sont enregistrées de façon anonyme et utilisées uniquement dans le cadre de cette recherche.', help_text='Texte de présentation / consentement (sauts de ligne respectés).')),
                ('bouton_consentement', models.CharField(default='Je consens et je commence', help_text='Libellé du bouton de consentement.', max_length=100)),
                ('intro_profil', models.TextField(blank=True, default="Ces questions ne sont posées qu'une seule fois et servent uniquement aux statistiques de l'étude. Vos réponses restent anonymes.", help_text="Texte d'introduction de la page de profil (questions posées une fois).")),
                ('texte_remerciement', models.TextField(default='Merci pour votre participation. Vos réponses ont bien été enregistrées ; vous pouvez fermer cette page.', help_text='Texte de la page de fin.')),
            ],
            options={
                'verbose_name': "configuration de l'étude",
                'verbose_name_plural': "configuration de l'étude",
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.SlugField(help_text="Identifiant court et stable, utilisé comme en-tête de colonne à l'export (ex. q1, age, clarte).", max_length=40, unique=True),
        ),
    ]
